name: Create new release candidate branch

on: workflow_dispatch

jobs:
  create-branch:
    name: Create new branch
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/ci/add-new-github-actions-pipeline'
    steps:
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-candidate-test'
