name: Create new release candidate branch

on: workflow_dispatch

jobs:
  create-branch:
    name: Create new branch
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/hotfix/')
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      # Calculate the next release version based on conventional semantic release
      - name: Create release branch
        id: create-release
        env:
          HUSKY: 0
        run: |
          source_branch_name=${GITHUB_REF##*/}
          git config --global --add safe.directory "$GITHUB_WORKSPACE" && git fetch origin main --depth=1
          git merge origin/main
          current_version=$(jq -r .version package.json)

          npm run release -- --skip.commit --skip.tag --skip.changelog
          new_version=$(jq -r .version package.json)
          git reset --hard

          branch_name="release/${new_version}"

          echo "Source branch for new release is $source_branch_name"
          echo "Current version is $current_version"
          echo "Release type is $release_type"
          echo "New version is $new_version"
          echo "New release branch name is $branch_name"

          echo "::set-output name=branch_name::$branch_name"
          echo "::set-output name=new_version::$new_version"

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/${{ steps.create-release.outputs.branch_name }}'
