name: Create new release fix branch

on:
  workflow_dispatch:
    inputs:
      fix_name:
        description: Fix branch name
        required: true

jobs:
  create-branch:
    name: Create new branch
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix-release/')
    steps:
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'fix/${{ github.event.inputs.fix_name }}'
