name: Create new hotfix branch

on:
  workflow_dispatch:
    inputs:
      hotfix_name:
        description: Hotfix branch name
        required: true

jobs:
  create-branch:
    name: Create new branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    if: github.ref == 'refs/heads/master-temp' || github.ref == 'refs/heads/main'
    steps:
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'hotfix-test/${{ github.event.inputs.hotfix_name }}'
