name: Draft new release

on: workflow_dispatch

jobs:
  draft-new-release:
    name: Draft a new release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix/')
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      # Calculate the next release version based on conventional semantic release
      - name: Create release branch
        id: create-release
        env:
          HUSKY: 0
        run: |
          source_branch_name=${GITHUB_REF##*/}
          release_type=release
          grep -q "hotfix/" <<< "${GITHUB_REF}" && release_type=hotfix-release
          git fetch origin main --depth=1
          git merge origin/main
          current_version=$(jq -r .version package.json)

          npm run release -- --skip.commit --skip.tag --skip.changelog
          new_version=$(jq -r .version package.json)
          git reset --hard

          branch_name="${release_type}/${new_version}"

          echo "Source branch for new release is $source_branch_name"
          echo "Current version is $current_version"
          echo "Release type is $release_type"
          echo "New version is $new_version"
          echo "New release branch name is $branch_name"
          git checkout -b "$branch_name"
          git push --set-upstream origin "$branch_name"

          echo "::set-output name=source_branch_name::$source_branch_name"
          echo "::set-output name=branch_name::$branch_name"
          echo "::set-output name=new_version::$new_version"

      - name: Update changelog & bump version
        env:
          HUSKY: 0
        run: |
          npm i -g conventional-changelog-cli
          SUMMARY=$(((npx conventional-changelog -u) 2>&1) | sed "s/*/<br> */g" | sed "s/#/ /g" | tr -d '\n' || true)
          echo $SUMMARY
          echo "::set-output name=commit_summary::$SUMMARY"
          npm run release

      - name: Push new version in release branch & tag
        run: |
          git push --follow-tags

      - name: Create pull request into main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.create-release.outputs.branch_name }}
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'chore(release): pulling ${{ steps.create-release.outputs.branch_name }} into main'
          pr_body: ":crown: *An automated PR*\n\n${{ steps.finish-release.outputs.commit_summary }}"
          pr_reviewer: 'ktgowtham'
